name: Deploy Next.js to Digital Ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.DO_SSH_HOST }}
      SSH_USER: ${{ secrets.DO_SSH_USER }}
      APP_DIR: /var/www/russian-gdp-landing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (22.x)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build (Next.js)
        run: yarn build

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Ensure remote app directory
        run: ssh "$SSH_USER@$SSH_HOST" "mkdir -p '$APP_DIR'"

      - name: Rsync dist (build output)
        run: rsync -avz --delete ./dist/ "$SSH_USER@$SSH_HOST:$APP_DIR/"
